# Quasi-cord の接続行列

In [1]:
import numpy as np

## Quasi-cord 定義

In [2]:
c = [1,1,1,1] 
#[3,2,1,4] #[3,4,5,2]
s = sum(c) + 1

In [3]:
print(s)

5


## 接続行列の生成

In [4]:
sh = [0, -(2*c[1]+1), -2*c[2], 0]

for i in range(len(c)):
    P1 = np.roll(np.eye(s, c[i], dtype=int), shift=sh[i], axis=0)
    P2 = np.roll(np.flip(P1, axis=1), shift=c[i], axis=0)
    P = P1+P2


[[1]
 [1]
 [0]
 [0]
 [0]]


In [4]:
T1 = np.roll(np.eye(s, c[0], dtype=int), shift=0, axis=0)
T2 = np.roll(np.flip(T1, axis=1), shift=c[0], axis=0)
T = T1+T2; print(T)

[[1]
 [1]
 [0]
 [0]
 [0]]


In [5]:
L1 = np.roll(np.eye(s, c[1], dtype=int), shift=-(2*c[1]+1), axis=0)
L2 = np.roll(np.flip(L1, axis=1), shift=c[1]+1, axis=0)
L = L1 + L2; print(L)

[[0]
 [0]
 [1]
 [0]
 [1]]


In [6]:
B1 = np.roll(np.eye(s, c[2], dtype=int), shift=-2*c[2], axis=0) * (-1)
B2 = np.roll(np.flip(B1, axis=1), shift=c[2], axis=0)
B = B1 + B2; print(B)

[[ 0]
 [ 0]
 [ 0]
 [-1]
 [-1]]


In [7]:
R1 = np.roll(np.eye(s, c[3], dtype=int), shift=0, axis=0) * (-1)
R2 = np.roll(np.flip(R1, axis=1), shift=c[3]+1, axis=0)
R = R1 + R2; print(R)

[[-1]
 [ 0]
 [-1]
 [ 0]
 [ 0]]


In [8]:
V = np.eye(s, 1, dtype=int)
L0 = np.roll(V, shift=-(c[1]+1), axis=0)
R0 = np.roll(V, shift=c[3], axis=0) * (-1)
C = np.roll(np.eye(1, s+1, dtype=int), shift=c[0]+c[1], axis=1)

M = np.r_[np.c_[T,L,L0,B,R,R0],C]
#M = np.c_[T,L,B,R,R0]
print(M)

[[ 1  0  0  0 -1  0]
 [ 1  0  0  0  0 -1]
 [ 0  1  0  0 -1  0]
 [ 0  0  1 -1  0  0]
 [ 0  1  0 -1  0  0]
 [ 0  0  1  0  0  0]]


In [9]:
np.linalg.det(M)

1.0

## TODO

[ ] 接続行列の生成について。quasi-cord が $\tau + \lambda = \beta + \rho$ の場合しかうまく行ってない。